packages:
  - .

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - astro
  - "@astrojs/*"
  - "@napi-rs/wasm-runtime"

overrides:
  wrangler: "4.114.0"
  typescript: "6.0.3"
  "@astrojs/compiler-rs": "latest"
