packages:
  - "pkgs/*"

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - astro
  - '@astrojs/*'
  - '@napi-rs/wasm-runtime'

overrides:
  "@astrojs/compiler-rs": "latest"
  "wrangler": "4.112.0"
  "hono": "4.12.30"
