packages:
  - "pkgs/*"

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - astro
  - '@astrojs/*'
  - '@napi-rs/wasm-runtime'

overrides:
  "@astrojs/compiler-rs": "^0.3.0"
