name = "web"
main = "dist/_worker.js/index.js"
compatibility_date = "2025-10-29"
dev.port = 4321

[assets]
binding = "ASSETS"
directory = "./dist"
not_found_handling = "404-page"

[[kv_namespaces]]
binding = "HITCOUNT"
id = "3f3992f9add44830ab84ba3071dcda10"

[observability]
enabled = true
