name: Deploy to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  frontend:
    name: Build and deploy frontend
    environment: prod
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"

      - name: Setup PNPM
        uses: pnpm/action-setup@v6
        with:
          version: 10.33.0
          cache: true

      - name: Install dependencies and build
        working-directory: pkgs/frontend
        run: |
          echo "${{ secrets.DOTENV }}" > .env
          pnpm install --prod --frozen-lockfile
          pnpm build

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: "latest"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: pkgs/frontend

  backend:
    name: Build and deploy backend
    environment: prod
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - name: Setup PNPM
        uses: pnpm/action-setup@v6
        with:
          version: 10.33.0

      - name: Install dependencies and build
        working-directory: pkgs/backend
        run: pnpm install --prod --frozen-lockfile

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: "latest"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: pkgs/backend
